//
//  BackpackInteractor.swift
//  Pokedex
//
//  Created by Jose Miguel Benedicto Ruiz on 31/3/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class BackpackInteractor {
}

// MARK: - Extensions -

extension BackpackInteractor: BackpackInteractorInterface {
    func getBackpack() -> [Pokemon] {
        return [.bulbasaur, .charmander, .pikachu, .mewtwo]
    }
}
