//
//  BackpackFormatter.swift
//  Pokedex
//
//  Created by Jose Miguel Benedicto Ruiz on 31/3/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class BackpackFormatter {
}

// MARK: - Extensions -

extension BackpackFormatter: BackpackFormatterInterface {
}
