//
//  BackpackInterfaces.swift
//  Pokedex
//
//  Created by Jose Miguel Benedicto Ruiz on 31/3/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol BackpackWireframeInterface: WireframeInterface {
}

protocol BackpackViewInterface: ViewInterface {
}

protocol BackpackPresenterInterface: PresenterInterface {
}

protocol BackpackFormatterInterface: FormatterInterface {
}

protocol BackpackInteractorInterface: InteractorInterface {
}
