//
//  BackpackInterfaces.swift
//  Pokedex
//
//  Created by Jose Miguel Benedicto Ruiz on 31/3/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol BackpackWireframeInterface: WireframeInterface {
    
}

protocol BackpackViewInterface: ViewInterface {
    func showEmptyBackpack()
    func showBackpackContents(_ contents: [Pokemon])
}

protocol BackpackPresenterInterface: PresenterInterface {
    func configure() -> Void
}

protocol BackpackFormatterInterface: FormatterInterface {
}

protocol BackpackInteractorInterface: InteractorInterface {
    func getBackpack() -> [Pokemon]
}
