//
//  BackpackViewController.swift
//  Pokedex
//
//  Created by Jose Miguel Benedicto Ruiz on 31/3/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import SnapKit

final class BackpackViewController: UIViewController {
    
    lazy private var sampleLabel: UILabel = {
        let label = UILabel()
        label.translatesAutoresizingMaskIntoConstraints = false
        label.text = "Hello World!"
        return label
    }()

    // MARK: - Public properties -

    var presenter: BackpackPresenterInterface!

    // MARK: - Lifecycle -
    
    func setupConstraints() {
        sampleLabel.snp.makeConstraints { (make) -> Void in
            make.centerX.equalTo(self.view)
            make.centerY.equalTo(self.view)
         }
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .white
        view.addSubview(sampleLabel)
        
        setupConstraints()
    }

}

// MARK: - Extensions -

extension BackpackViewController: BackpackViewInterface {
}
